### ISSUE TITLE
Can't load libgsl.19.dylib

### ISSUE THREAD

**Issue by mcg1969** [AnacondaRecipes/r-gsl-feedstock#1]
I built an env with the following packages (among others):
```
    gsl:             2.4-h1de35cc_4
    r-base:          3.4.3-h9b62496_0       
    r-gsl:           1.9_10.3-r343h7f474d2_0
```
This is what I'm seeing:
```
> library("gsl")
Error: package or namespace load failed for ‘gsl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/mgrant/miniconda3/envs/rgsl/lib/R/library/gsl/libs/gsl.so':
  dlopen(/Users/mgrant/miniconda3/envs/rgsl/lib/R/library/gsl/libs/gsl.so, 6): Library not loaded: @rpath/libgsl.19.dylib
  Referenced from: /Users/mgrant/miniconda3/envs/rgsl/lib/R/library/gsl/libs/gsl.so
  Reason: image not found
```

**Comment by mcg1969** [comment]
Looks like the `gsl` package is installing `libgsl.23.dylib`, not `libgsl.19.dylib`. A symbolic link enables it to load, at least.

**Comment by mcg1969** [comment]
On the Mac, at least, `install_name_tool -change @rpath/libgsl.19.dylib @rpath/libgsl.dylib gsl.so` seems to fix it as well

**Comment by mcg1969** [comment]
Rebuilding the package also works. But that means the metadata for this package is just wrong—it needs to somehow pin to the specific build of gsl so that it can pick up `libgsl.19.dylib`. Shouldn't we instead try and have it link to the unversioned `libgsl.dylib` instead, and use dependency constraints to do a more gentle gating?

cc: @mingwandroid, thoughts?

**Comment by mingwandroid** [comment]
> Shouldn't we instead try and have it link to the unversioned `libgsl.dylib` instead, and use dependency constraints to do a more gentle gating?

No, that file is only a symlink to the real `libgsl.23.dylib`:

```
-rwxrwxr-x   1 rdonnelly  staff  2582516 11 Jun 17:10 libgsl.23.dylib
-rw-rw-r--  14 rdonnelly  staff  4100624 11 Jun 17:10 libgsl.a
lrwxr-xr-x   1 rdonnelly  staff       15 12 Jun 12:36 libgsl.dylib -> libgsl.23.dylib
-rwxrwxr-x   1 rdonnelly  staff      972 11 Jun 17:10 libgsl.la
-rwxrwxr-x   1 rdonnelly  staff   305812 11 Jun 17:10 libgslcblas.0.dylib
-rw-rw-r--  14 rdonnelly  staff   420544 11 Jun 17:10 libgslcblas.a
lrwxr-xr-x   1 rdonnelly  staff       19 12 Jun 12:36 libgslcblas.dylib -> libgslcblas.0.dylib
-rwxrwxr-x   1 rdonnelly  staff      999 11 Jun 17:10 libgslcblas.la
drwxr-xr-x   3 rdonnelly  staff       96 12 Jun 12:36 pkgconfig
```

.. so the `LC_ID_DYLIB` (from `otool -l`) is:

```
Load command 3
          cmd LC_ID_DYLIB
      cmdsize 48
         name @rpath/libgsl.23.dylib (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 24.0.0
compatibility version 24.0.0
```

.. when Apple's linker (`ld64`) sees this that is the name that gets transferred into the thing linking to this DSO (in an `LC_LOAD_DYLIB` command). The `current version` and `compatibility version` are also important for macOS load-a-bility.

It seems `r-gsl` for `R 3.4.3` was built at a time when the latest released `gsl` had no [`run-exports`](https://github.com/AnacondaRecipes/gsl-feedstock/blob/master/recipe/meta.yaml#L18-L21) so `gsl` ends up unpinned. Rebuilding it will fix it, I'll do that first thing tomorrow. BTW Linux is similarly broken.

**Comment by mingwandroid** [comment]
I've uploaded these now for R and MRO (build #1).

**Comment by mcg1969** [comment]
Thank you!

**Comment by mingwandroid** [comment]
No problem! You may need to force the use of the Anaconda R channel until they sync across
